services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - DEBUG "true"
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init script, which creates all the relevant db tables.
  app:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DEBUG=true
      - DB_HOST=$DB_HOSTNAME
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true

volumes: 
  postgres_data: