services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    env_file: ../.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init script, which creates all the relevant db tables.
  app:
    depends_on:
      - db
    build: .
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=5432
    stdin_open: true
    tty: true

volumes: 
  postgres_data: